server:
  port: 8003
spring:
  application:
    name: GATEWAY
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
    gateway:
      #配置路由
      routes:
        - id: PROVIDER  #路由id，没有固定规则，建议使用服务名
          uri: lb://PROVIDER #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/**  # 断言，路径相匹配的进行路由
