server:
  port: 9001
spring:
  redis:
    host: 127.0.0.1
    database: 2
  rabbitmq:
    host: 39.105.59.91
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
